### ISSUE TITLE
django 1.8 The SchemaEditorClass is None

### ISSUE THREAD

**Issue by jbrissier** [lionheart/django-pyodbc#110]
I try to use django-pyodbc with django 1.7 / 1.8 but i always get the following error: 

```
'The SchemaEditorClass attribute of this database wrapper is still None')
NotImplementedError: The SchemaEditorClass attribute of this database wrapper is still None
```

**My environment:** 
Django (1.8.11)
django-pyodbc (0.3.0)
pip (7.1.2)
pyodbc (3.0.10)
setuptools (18.2)
wheel (0.24.0)
python 2.7.11

Are migrations supported? Should i disabled them?

**Comment by individual-it** [comment]
same problem here, any solutions?

**Comment by dulabs** [comment]
bump! +1

**Comment by microcomet** [comment]
same problem, is this a bug or something wrong in my settings?

**Comment by shadiakiki1986** [comment]
Any solutions yet?

**Comment by RossRogers** [comment]
Unfortunately, not at this time due to contributors being slammed.

**Comment by RossRogers** [comment]
This issue is resolved on the trunk and in alpha release 2.0.0a1, using Django 2.0.   I am closing this issue, but if this is an unacceptable outcome, please re-open the ticket.  If you require this to be backported to the [django-1 branch](https://github.com/lionheart/django-pyodbc/commit/f510afd69be15ea18593ae6b4b14e0386eafa758) then please feel free to re-open this ticket.  Unfortunately, it is likely to remain unresolved, as there may not be any takers on this backporting task.  Apologies.

**Comment by brianedelman** [comment]
Unfortunately this is still an issue for me with 2.0.0a1 using Django 2.0.2 as well.
